# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('charitable_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
