# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('grant_requested', models.CharField(max_length=255)),
                ('grant_awarded', models.CharField(max_length=255)),
                ('funds_not_used', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('partnership', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('grant_stream', models.CharField(max_length=255)),
                ('fund', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('community_impact', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'grants',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_funds_required', models.CharField(max_length=255)),
                ('date_reports_due', models.CharField(max_length=255)),
                ('reports_received', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'schedules',
            },
        ),
    ]
