# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_auto_20170713_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'files'},
        ),
        migrations.AddField(
            model_name='file',
            name='attachment',
            field=models.FileField(default=None, upload_to='attachments'),
        ),
    ]
