# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0007_auto_20170713_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_funds_required',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_reports_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reports_received',
            field=models.DateField(),
        ),
    ]
