# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0008_auto_20170713_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='community_impact',
            field=models.TextField(max_length=10000),
        ),
    ]
