# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0010_auto_20170713_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['organization_name'], 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['project_name'], 'verbose_name_plural': 'grants'},
        ),
    ]
